spring.datasource.url=${DB_URL:jdbc:postgresql://ep-morning-pond-apcz3rm8-pooler.c-7.us-east-1.aws.neon.tech/brunch_db?sslmode=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_7aSCWVt0YKFG}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=${MAIL_USER:resend}
spring.mail.password=${MAIL_PASSWORD:re_P2yy2shc_PzAqDvwsKSxr1qQceZ2QwiK4}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
