# =============================================
#   Cambia el perfil activo según donde trabajes
#
#   local → pgAdmin (PostgreSQL local)
#   neon  → Neon (PostgreSQL en la nube)
# =============================================
spring.profiles.active=neon

# Servidor
server.port=8080
