-- Esquema base heredado de los microservicios Spring Boot (Hibernate ddl-auto).
-- Escrito a mano desde pg_dump para conservar las columnas IDENTITY y las
-- restricciones CHECK, que Prisma no genera por su cuenta.

CREATE TABLE "usuarios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cuenta_google" BOOLEAN NOT NULL,
    "dos_fa_activo" BOOLEAN NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "nombre" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "rol" VARCHAR(255),
    "suscrito" BOOLEAN DEFAULT false,
    CONSTRAINT "usuarios_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "ukkfsp0s1tflm1cwlj8idhqsad0" UNIQUE ("email"),
    CONSTRAINT "usuarios_rol_check" CHECK ("rol" IN ('ADMIN', 'USUARIO'))
);

CREATE TABLE "categorias" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" VARCHAR(255) NOT NULL,
    CONSTRAINT "categorias_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "ukqcog8b7hps1hioi9onqwjdt6y" UNIQUE ("nombre")
);

CREATE TABLE "menu_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "descripcion" TEXT,
    "disponible" BOOLEAN NOT NULL,
    "imagen_url" VARCHAR(255),
    "nombre" VARCHAR(255) NOT NULL,
    "precio" DECIMAL(38,2),
    "categoria_id" BIGINT,
    CONSTRAINT "menu_items_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk8jufm10ou3keb2efyccs8tsee" FOREIGN KEY ("categoria_id") REFERENCES "categorias"("id")
);

CREATE TABLE "pedidos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "direccion" VARCHAR(255) NOT NULL,
    "estado" VARCHAR(255),
    "fecha_creacion" TIMESTAMP(6),
    "fecha_programada" TIMESTAMP(6),
    "metodo_pago" VARCHAR(255),
    "notas" VARCHAR(255),
    "telefono" VARCHAR(255) NOT NULL,
    "total" DECIMAL(38,2),
    "usuario_id" BIGINT,
    CONSTRAINT "pedidos_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "pedidos_estado_check" CHECK ("estado" IN ('PENDIENTE', 'EN_PREPARACION', 'EN_CAMINO', 'ENTREGADO', 'CANCELADO'))
);

CREATE TABLE "detalles_pedido" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cantidad" INTEGER NOT NULL,
    "menu_item_id" BIGINT,
    "precio_unitario" DECIMAL(38,2),
    "pedido_id" BIGINT,
    CONSTRAINT "detalles_pedido_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fk4qmqlxyy78kjl4ec4wjnfmggu" FOREIGN KEY ("pedido_id") REFERENCES "pedidos"("id"),
    CONSTRAINT "detalles_pedido_cantidad_check" CHECK ("cantidad" >= 1)
);

CREATE TABLE "reservas" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "estado" VARCHAR(20) DEFAULT 'PENDIENTE',
    "fecha" DATE NOT NULL,
    "hora" TIME(6) NOT NULL,
    "nombre" VARCHAR(255) NOT NULL,
    "notas" VARCHAR(255),
    "ocasion" VARCHAR(255),
    "personas" INTEGER NOT NULL,
    "usuario_id" BIGINT,
    CONSTRAINT "reservas_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "reservas_estado_check" CHECK ("estado" IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA')),
    CONSTRAINT "reservas_personas_check" CHECK ("personas" >= 1)
);

CREATE TABLE "mensajes_contacto" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "fecha_envio" TIMESTAMP(6),
    "mensaje" TEXT NOT NULL,
    "nombre" VARCHAR(255) NOT NULL,
    "telefono" VARCHAR(255),
    CONSTRAINT "mensajes_contacto_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "audit_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "accion" VARCHAR(255) NOT NULL,
    "detalle" VARCHAR(500) NOT NULL,
    "fecha" TIMESTAMP(6) NOT NULL,
    "servicio" VARCHAR(255) NOT NULL,
    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);
